apiVersion: v1
kind: Service
metadata:
  name: internal-web
  namespace: homework
spec:
  selector:
    app: web-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http