apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: web-server
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.0
        ports:
        - containerPort: 8000
        lifecycle:
        preStop:
          exec:
            command: ["rm", "/homework/index.html"]
      volumeMounts:
      - name: workdir
        mountPath: /homework
      - mountPath: /etc/nginx
        readOnly: true
        name: nginx-conf
      initContainers:
      - name: init
        image: busybox:1.36
        command:
        - wget
        - "-O"
        - "/init/index.html"
        - http://info.cern.ch
      volumeMounts:
      - name: workdir
        mountPath: "/init"
      volumes:
      - name: workdir
        emptyDir: {}
      - name: nginx-conf
        configMap:
          name: nginx-conf
            items:
            - key: nginx.conf
              path: nginx.conf